import type { Metadata } from "next";
import "./globals.css";
import {Instrument_Sans} from "next/font/google"
import SmoothScroll from "./components/SmoothScroll";

const InstrumentSans = Instrument_Sans({
  subsets : ['latin'], 
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${InstrumentSans.className} antialiased`}
      >
        <SmoothScroll />
        {children}
      </body>
    </html>
  );
}
